### ISSUE TITLE
Kafka topics, producers, consumers auto-discovery?

### ISSUE THREAD

**Issue by deitch** [newrelic/k8s-webhook#27]
Can the Kafka sidecar auto-discover consumer groups, producers, topics? I am looking at the sample [here](https://github.com/newrelic/k8s-webhook/blob/master/examples/kafka.yaml). The configuration implies [here](https://github.com/newrelic/k8s-webhook/blob/master/examples/kafka.yaml#L465-L467) that I need to specify the producers and consumers, and [here](https://github.com/newrelic/k8s-webhook/blob/master/examples/kafka.yaml#L488) that I need to specify the consumer groups. Can it discover them so I don't have to specify?

Separately, it does seem to imply [here](https://github.com/newrelic/k8s-webhook/blob/master/examples/kafka.yaml#L480) that it can discover topics with `topic_mode: all`.

Thanks

**Comment by mariomac** [comment]
Hi @deitch ,

you are right. You can collect all the topics with the `topic_mode: all`, but you need to specify both `consumers` and `producers`. You can also provide a whitelist of `consumer_groups` in which to collect offset data for.

Please refer to the [official nri-kafka configuration document](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration) for more details about those options.

**Comment by ikavanaghNR** [comment]
Hi, my name is Ian, I'm a PM with New Relic Infrastructure. Thanks for reaching out to us.

For topics, you are correct in that you could set the parameter to all and it will monitor all topics.

For consumers and producers however, they need to be added to the config file.

If you hve any other questions, please let me know.

Best,

Ian

**Comment by deitch** [comment]
Thanks for the response and link, @mariomac. 

Hi @ikavanaghNR , I read your Word doc, thanks for that and responding here. 

OK, so if I want consumer lag, I need either to list them explicitly, or list the groups explicitly. Is that correct?
